/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jni_Mandelbrot_Mandelbrot */

#ifndef _Included_com_jni_Mandelbrot_Mandelbrot
#define _Included_com_jni_Mandelbrot_Mandelbrot
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jni_Mandelbrot_Mandelbrot
 * Method:    coords
 * Signature: (FFFI)[I
 */
JNIEXPORT jintArray JNICALL Java_com_jni_Mandelbrot_Mandelbrot_coords
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jint);

#ifdef __cplusplus
}
#endif
#endif
