/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jni_Hello_Hello */

#ifndef _Included_com_jni_Hello_Hello
#define _Included_com_jni_Hello_Hello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jni_Hello_Hello
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jni_Hello_Hello_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
