/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jni_Balls_Balls */

#ifndef _Included_com_jni_Balls_Balls
#define _Included_com_jni_Balls_Balls
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jni_Balls_Balls
 * Method:    start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jni_Balls_Balls_start
  (JNIEnv *, jobject);

/*
 * Class:     com_jni_Balls_Balls
 * Method:    ballPositions
 * Signature: (Ljava/lang/Class;)[Lcom/jni/Balls/Balls/Pos;
 */
JNIEXPORT jobjectArray JNICALL Java_com_jni_Balls_Balls_ballPositions
  (JNIEnv *, jobject, jclass);

#ifdef __cplusplus
}
#endif
#endif
